from __future__ import annotations
import re
from core.domain import DeviceDomain
from core.renderer import register_renderer
from core.renderer.base import BaseRenderer, RenderContext, RenderResult, ReviewItem
from core.renderer.shared import render_vlan_range
from core.ir_models import IRConfig
from core.ir_models.enums import IRInterfaceType


class CiscoIOSXERenderer(BaseRenderer):
    vendor = "cisco"
    platform = "ios-xe"
    comment_char = "!"

    def render(self, ir: IRConfig, context: RenderContext | None = None) -> RenderResult:
        ctx = context or RenderContext(comment_char=self.comment_char)
        parts: list[str] = []
        features_rendered: list[str] = []
        features_skipped: list[str] = []
        review_items: list[ReviewItem] = []

        if ctx.render_header:
            parts.append(f"{ctx.comment_char} Generated by Network Translator")
            parts.append(f"{ctx.comment_char} Source: {ir.meta.source_vendor}/{ir.meta.source_platform} -> Target: {ir.meta.target_vendor}/{ir.meta.target_platform}")
            parts.append("")

        if ir.meta.hostname:
            parts.append(f"hostname {ir.meta.hostname}")
            parts.append("")

        if ir.vlans:
            parts.append("!")
            parts.append("! VLAN Configuration")
            parts.append("!")
            for vlan in sorted(ir.vlans, key=lambda v: v.vid):
                parts.append(f"vlan {vlan.vid}")
                if vlan.name:
                    parts.append(f" name {vlan.name}")
            parts.append("")
            features_rendered.append("vlans")

        if ir.stp:
            parts.append("!")
            parts.append("! Spanning-Tree Configuration")
            parts.append("!")
            if ir.stp.mode and "mst" in ir.stp.mode.lower():
                parts.append("spanning-tree mst configuration")
                if ir.stp.region:
                    parts.append(f" name {ir.stp.region}")
                for inst in ir.stp.instances:
                    vlans = inst.get("vlans", [])
                    vlan_str = render_vlan_range(vlans) if vlans else ""
                    if vlan_str and inst.get("id") is not None:
                        parts.append(f" instance {inst['id']} vlan {vlan_str}")
                parts.append(" exit")
                parts.append("spanning-tree mode mst")
                parts.append("")
            review_items.append(ReviewItem(
                field="stp", severity="info",
                description="STP/MST configuration migrated. Root bridge priorities may differ between H3C and Cisco MST implementations."
            ))
            features_rendered.append("stp")

        if ir.lags:
            parts.append("!")
            parts.append("! Port-Channel Configuration")
            parts.append("!")
            for lag in ir.lags:
                parts.append(f"interface Port-channel{lag.lag_id}")
                is_dynamic = lag.mode.lower() == "lacp"
                member_mode = "active" if is_dynamic else "on"
                parts.append(f"! NOTE: {'dynamic' if is_dynamic else 'static'} LAG - member interfaces use channel-group {lag.lag_id} mode {member_mode}")
            parts.append("")
            features_rendered.append("lacp")

        phys_interfaces = [i for i in ir.interfaces if i.iftype == IRInterfaceType.PHYSICAL]
        loopbacks = [i for i in ir.interfaces if i.iftype == IRInterfaceType.LOOPBACK]
        nulls = [i for i in ir.interfaces if i.iftype == IRInterfaceType.NULL]

        if phys_interfaces or loopbacks or nulls:
            parts.append("!")
            parts.append("! Interface Configuration")
            parts.append("!")
            for iface in phys_interfaces:
                parts.append(f"interface {iface.name}")
                if iface.description:
                    parts.append(f" description {iface.description}")
                if iface.untagged_vlan is not None:
                    parts.append(" switchport mode access")
                    parts.append(f" switchport access vlan {iface.untagged_vlan}")
                elif iface.trunk_allowed_all:
                    parts.append(" switchport mode trunk")
                    parts.append(" switchport trunk allowed vlan all")
                elif iface.trunk_allowed:
                    parts.append(" switchport mode trunk")
                    vlan_str = render_vlan_range(iface.trunk_allowed)
                    parts.append(f" switchport trunk allowed vlan {vlan_str}")
                if iface.lag_group:
                    lag_obj = next((lag for lag in ir.lags if lag.lag_id == iface.lag_group), None)
                    is_dynamic = lag_obj is None or lag_obj.mode.lower() == "lacp"
                    member_mode = "active" if is_dynamic else "on"
                    parts.append(f" channel-group {iface.lag_group} mode {member_mode}")
                if iface.shutdown:
                    parts.append(" shutdown")
                else:
                    parts.append(" no shutdown")
                parts.append("")
            for iface in loopbacks:
                parts.append(f"interface {iface.name}")
                if iface.description:
                    parts.append(f" description {iface.description}")
                if iface.ip and iface.mask:
                    parts.append(f" ip address {iface.ip} {iface.mask}")
                if iface.shutdown:
                    parts.append(" shutdown")
                else:
                    parts.append(" no shutdown")
                parts.append("")
            for iface in nulls:
                parts.append(f"interface {iface.name}")
                parts.append(" no ip address")
                parts.append("")
            features_rendered.append("interfaces")

        if ir.svis:
            parts.append("!")
            parts.append("! SVI Configuration")
            parts.append("!")
            for svi in sorted(ir.svis, key=lambda s: s.vid):
                parts.append(f"interface Vlan{svi.vid}")
                if svi.description:
                    parts.append(f" description {svi.description}")
                if svi.ip and svi.mask:
                    parts.append(f" ip address {svi.ip} {svi.mask}")
                for fhrp in svi.fhrp:
                    parts.append(f" vrrp {fhrp.group_id} ip {fhrp.virtual_ip}")
                    if fhrp.priority != 100:
                        parts.append(f" vrrp {fhrp.group_id} priority {fhrp.priority}")
                    review_items.append(ReviewItem(
                        field="fhrp", severity="info",
                        description=f"VRRP group {fhrp.group_id} migrated. Preempt behavior may differ between H3C and Cisco implementations."
                    ))
                if svi.acl_in:
                    parts.append(f" ip access-group {svi.acl_in} in")
                if svi.acl_out:
                    parts.append(f" ip access-group {svi.acl_out} out")
                if svi.shutdown:
                    parts.append(" shutdown")
                else:
                    parts.append(" no shutdown")
                parts.append("")
            features_rendered.append("svis")

        if ir.static_routes:
            parts.append("!")
            parts.append("! Static Route Configuration")
            parts.append("!")
            for route in ir.static_routes:
                cmd = f"ip route {route.prefix} {route.mask} {route.nexthop}"
                if route.metric is not None:
                    cmd += f" {route.metric}"
                parts.append(cmd)
            parts.append("")
            features_rendered.append("static_routes")

        if ir.ospf:
            parts.append("!")
            parts.append("! OSPF Configuration")
            parts.append("!")
            for ospf in ir.ospf:
                parts.append(f"router ospf {ospf.process_id}")
                if ospf.router_id:
                    parts.append(f" router-id {ospf.router_id}")
                static_redist = False
                for r in ospf.redistributes:
                    if isinstance(r, dict):
                        proto = r.get("protocol", "")
                    else:
                        proto = str(r)
                    if "static" in proto.lower():
                        static_redist = True
                        break
                if static_redist or not ospf.redistributes:
                    parts.append(" redistribute static subnets")
                parts.append(" passive-interface default")
                if ospf.review_notes:
                    silent_matches = re.findall(r"Vlan-?interface\s*(\d+)", ospf.review_notes)
                    for iface_num in silent_matches:
                        parts.append(f" no passive-interface Vlan{iface_num}")
                for net in ospf.networks:
                    area_str = net.get("area", "0.0.0.0")
                    if area_str == "0.0.0.0":
                        area_str = "0"
                    ip = net.get("ip", "")
                    wildcard = net.get("wildcard", "0.0.0.0")
                    if ip:
                        parts.append(f" network {ip} {wildcard} area {area_str}")
                parts.append(" exit")
                parts.append("")
            features_rendered.append("ospf")

        if ir.acls:
            parts.append("!")
            parts.append("! ACL Configuration")
            parts.append("!")
            for acl in ir.acls:
                is_standard = acl.acl_type in ("basic", "standard")
                if is_standard or (acl.number is not None and acl.number < 100):
                    parts.append(f"access-list {acl.number} permit any")
                else:
                    parts.append(f"ip access-list extended {acl.number}")
                    for entry in acl.entries:
                        seq = entry.sequence if entry.sequence is not None else 0
                        action = entry.action
                        if entry.src and entry.src_wildcard:
                            if entry.src_wildcard == "0":
                                src_str = f"host {entry.src}"
                            else:
                                src_str = f"{entry.src} {entry.src_wildcard}"
                        else:
                            src_str = "any"
                        has_dst = entry.dst is not None
                        if has_dst:
                            if entry.dst_wildcard == "0":
                                dst_str = f"host {entry.dst}"
                            else:
                                dst_str = f"{entry.dst} {entry.dst_wildcard}"
                        else:
                            dst_str = "any"
                        proto = entry.protocol if entry.protocol else "ip"
                        parts.append(f" {seq} {action} {proto} {src_str} {dst_str}")
            parts.append("")
            features_rendered.append("acls")

        if ir.management:
            parts.append("!")
            parts.append("! Management Configuration")
            parts.append("!")
            management = ir.management
            if management.dns:
                dns_raw = management.dns.get("raw", "") if isinstance(management.dns, dict) else str(management.dns)
                if "lldp" in dns_raw.lower() or "lldp" in str(management.dns).lower():
                    parts.append("lldp run")
            if management.snmp:
                for snmp_raw in management.snmp:
                    raw = snmp_raw.get("raw", "") if isinstance(snmp_raw, dict) else str(snmp_raw)
                    m = re.match(r"snmp-agent community read (\S+)\s+acl\s+(\d+)", raw)
                    if m:
                        parts.append(f"snmp-server community {m.group(1)} RO {m.group(2)}")
            if management.ntp:
                for ntp_raw in management.ntp:
                    raw = ntp_raw.get("raw", "") if isinstance(ntp_raw, dict) else str(ntp_raw)
                    m = re.match(r"ntp-service unicast-server (\S+)", raw)
                    if m:
                        parts.append(f"ntp server {m.group(1)}")
            if management.ssh:
                parts.append("ip ssh version 2")
            if management.syslog:
                has_lb_source = False
                for syslog_raw in management.syslog:
                    raw = syslog_raw.get("raw", "") if isinstance(syslog_raw, dict) else str(syslog_raw)
                    m = re.match(r"info-center loghost\s+(\S+)", raw)
                    if m:
                        parts.append(f"logging host {m.group(1)}")
                    if "source" in raw.lower() and "loop" in raw.lower():
                        has_lb_source = True
                if has_lb_source:
                    parts.append("logging source-interface Loopback0")
            parts.append("")
            features_rendered.append("management")

        if ir.aaa:
            parts.append("!")
            parts.append("! AAA Configuration - Requires Manual Review")
            parts.append("!")
            parts.append(f"{ctx.comment_char} Original HWTACACS config commented below:")
            aaa = ir.aaa
            if aaa.servers:
                for server in aaa.servers:
                    raw = server.get("raw", "") if isinstance(server, dict) else str(server)
                    if raw.strip():
                        parts.append(self.render_as_comment(raw, ctx.comment_char))
            parts.append("")
            features_skipped.append("aaa")
            review_items.append(ReviewItem(
                field="aaa", severity="warning",
                description="AAA configuration (HWTACACS/domain/local-user) requires manual review and redesign for Cisco IOS-XE."
            ))

        if ctx.render_unknown_blocks and ir.unknown_blocks:
            parts.append("!")
            parts.append("! UNSUPPORTED: Original config that could not be translated")
            parts.append("!")
            for ub in ir.unknown_blocks:
                commented = self.render_as_comment(ub.raw_text, ctx.comment_char)
                if commented.strip():
                    parts.append(commented)
            parts.append("")

        if ctx.render_unsupported and ir.unsupported:
            parts.append("!")
            parts.append("! UNSUPPORTED FEATURES (not translated):")
            parts.append("!")
            for u in ir.unsupported:
                commented = self.render_as_comment(u.raw_text, ctx.comment_char)
                if commented.strip():
                    parts.append(commented)
            parts.append("")

        parts.append("end")

        text = "\n".join(parts)
        text = self.format_output(text)

        return RenderResult(
            config_text=text,
            features_rendered=features_rendered,
            features_skipped=features_skipped,
            review_items=review_items,
        )


for _domain in [DeviceDomain.SWITCH, DeviceDomain.ROUTER]:
    register_renderer(_domain, "ios-xe", CiscoIOSXERenderer)
