from __future__ import annotations
from core.domain import DeviceDomain
from core.renderer import register_renderer
from core.renderer.base import BaseRenderer, RenderContext, RenderResult
from core.ir_models import IRConfig


class DPtechFWRenderer(BaseRenderer):
    vendor = "dptech"
    platform = "dp-firewall"
    comment_char = "!"

    def render(self, ir: IRConfig, context: RenderContext | None = None) -> RenderResult:
        ctx = context or RenderContext(comment_char=self.comment_char)
        parts: list[str] = []
        if ctx.render_header:
            parts.append(f"{ctx.comment_char} Generated by Network Translator")
            parts.append("")
        if ctx.render_unknown_blocks:
            for ub in ir.unknown_blocks:
                commented = self.render_as_comment(ub.raw_text, ctx.comment_char)
                if commented.strip():
                    parts.append(commented)
                    parts.append("")
        if ctx.render_unsupported:
            for u in ir.unsupported:
                commented = self.render_as_comment(u.raw_text, ctx.comment_char)
                if commented.strip():
                    parts.append(commented)
                    parts.append("")
        text = "\n".join(parts)
        text = self.format_output(text)
        return RenderResult(config_text=text, features_rendered=[], features_skipped=["all"])


register_renderer(DeviceDomain.FIREWALL, "dp-firewall", DPtechFWRenderer)
