from __future__ import annotations
from core.domain import DeviceDomain
from core.renderer import register_renderer
from core.renderer.base import BaseRenderer, RenderContext, RenderResult
from core.ir_models import IRConfig


class CiscoIOSXERenderer(BaseRenderer):
    vendor = "cisco"
    platform = "ios-xe"
    comment_char = "!"

    def render(self, ir: IRConfig, context: RenderContext | None = None) -> RenderResult:
        ctx = context or RenderContext(comment_char=self.comment_char)
        parts: list[str] = []

        # Header
        if ctx.render_header:
            parts.append(f"{ctx.comment_char} Generated by Network Translator")
            parts.append(f"{ctx.comment_char} Source: {ir.meta.source_vendor}/{ir.meta.source_platform}")
            parts.append(f"{ctx.comment_char} Target: {ir.meta.target_vendor}/{ir.meta.target_platform}")
            parts.append("")

        # Hostname
        if ir.meta.hostname:
            parts.append(f"hostname {ir.meta.hostname}")
            parts.append("")

        # Render unknown blocks as comments only
        if ctx.render_unknown_blocks:
            for ub in ir.unknown_blocks:
                commented = self.render_as_comment(ub.raw_text, ctx.comment_char)
                if commented.strip():
                    parts.append(commented)
                    parts.append("")

        # Render unsupported as comments only
        if ctx.render_unsupported:
            for u in ir.unsupported:
                commented = self.render_as_comment(u.raw_text, ctx.comment_char)
                if commented.strip():
                    parts.append(commented)
                    parts.append("")

        text = "\n".join(parts)
        text = self.format_output(text)

        return RenderResult(
            config_text=text,
            features_rendered=[],
            features_skipped=["vlans", "interfaces", "svis", "static_routes", "acls", "ospf", "stp", "lags", "management", "aaa"],
        )


for _domain in [DeviceDomain.SWITCH, DeviceDomain.ROUTER]:
    register_renderer(_domain, "ios-xe", CiscoIOSXERenderer)
