import pytest
from core.renderer import (
    register_renderer, get_renderer, list_renderers, init_renderers, DomainPlatformKey,
)
from core.domain import DeviceDomain
from core.renderer.base import BaseRenderer
from core.ir_models import IRConfig, IRConfigMeta


class TestRegistry:
    def test_init_registers_all(self):
        init_renderers()
        registered = list_renderers()
        keys = set(registered)

        assert (DeviceDomain.SWITCH, "ios-xe") in keys
        assert (DeviceDomain.ROUTER, "ios-xe") in keys
        assert (DeviceDomain.SWITCH, "comware") in keys
        assert (DeviceDomain.ROUTER, "comware") in keys
        assert (DeviceDomain.SWITCH, "vrp") in keys
        assert (DeviceDomain.ROUTER, "vrp") in keys
        assert (DeviceDomain.FIREWALL, "usg") in keys
        assert (DeviceDomain.SWITCH, "rg-os") in keys
        assert (DeviceDomain.ROUTER, "rg-os") in keys
        assert (DeviceDomain.FIREWALL, "stoneos") in keys
        assert (DeviceDomain.FIREWALL, "tos") in keys
        assert (DeviceDomain.FIREWALL, "dp-firewall") in keys

    def test_get_cisco_ios_xe_switch(self):
        init_renderers()
        cls = get_renderer(DeviceDomain.SWITCH, "ios-xe")
        assert cls is not None
        assert cls.vendor == "cisco"

    def test_get_huawei_usg_firewall(self):
        init_renderers()
        cls = get_renderer(DeviceDomain.FIREWALL, "usg")
        assert cls is not None
        assert cls.vendor == "huawei"

    def test_get_nonexistent_returns_none(self):
        cls = get_renderer(DeviceDomain.FIREWALL, "nonexistent")
        assert cls is None


class TestSkeletonRenderer:
    def test_cisco_renders_header(self):
        init_renderers()
        from core.ir_models import IRConfig, IRConfigMeta
        cls = get_renderer(DeviceDomain.SWITCH, "ios-xe")
        r = cls()
        meta = IRConfigMeta(source_vendor="h3c", target_vendor="cisco",
            source_domain=DeviceDomain.SWITCH, target_domain=DeviceDomain.SWITCH,
            source_platform="comware", target_platform="ios-xe")
        ir = IRConfig(meta=meta)
        result = r.render(ir)
        assert "Generated by Network Translator" in result.config_text
        assert result.config_text.endswith("\n")

    def test_cisco_hostname(self):
        init_renderers()
        cls = get_renderer(DeviceDomain.SWITCH, "ios-xe")
        r = cls()
        meta = IRConfigMeta(source_vendor="h3c", target_vendor="cisco",
            source_domain=DeviceDomain.SWITCH, target_domain=DeviceDomain.SWITCH,
            source_platform="comware", target_platform="ios-xe", hostname="SW01")
        ir = IRConfig(meta=meta)
        result = r.render(ir)
        assert "hostname SW01" in result.config_text

    def test_unknown_blocks_as_comments(self):
        init_renderers()
        from core.ir_models import IRConfig, IRConfigMeta, IRUnknownBlock
        from core.ir_models.enums import IRType
        from core.ir_models.base import SourceSpan
        cls = get_renderer(DeviceDomain.SWITCH, "ios-xe")
        r = cls()
        meta = IRConfigMeta(source_vendor="h3c", target_vendor="cisco",
            source_domain=DeviceDomain.SWITCH, target_domain=DeviceDomain.SWITCH,
            source_platform="comware", target_platform="ios-xe")
        ir = IRConfig(meta=meta)
        span = SourceSpan(start_line=1, end_line=1)
        ir.unknown_blocks.append(IRUnknownBlock(type=IRType.UNKNOWN, source_span=span, raw_text="vlan 10\n name test"))
        result = r.render(ir)
        # Unknown blocks must be commented out
        assert "! vlan 10" in result.config_text
        assert "! name test" in result.config_text
        # Raw command must NOT appear uncommented
        assert "\nvlan 10\n" not in result.config_text
        assert "\n name test\n" not in result.config_text

    def test_h3c_comment_char(self):
        init_renderers()
        cls = get_renderer(DeviceDomain.SWITCH, "comware")
        r = cls()
        meta = IRConfigMeta(source_vendor="h3c", target_vendor="cisco",
            source_domain=DeviceDomain.SWITCH, target_domain=DeviceDomain.SWITCH,
            source_platform="comware", target_platform="ios-xe")
        ir = IRConfig(meta=meta)
        result = r.render(ir)
        assert "! Generated by" in result.config_text

    def test_huawei_comment_char(self):
        init_renderers()
        from core.ir_models import IRConfig, IRConfigMeta, IRUnknownBlock
        from core.ir_models.enums import IRType
        from core.ir_models.base import SourceSpan
        cls = get_renderer(DeviceDomain.SWITCH, "vrp")
        r = cls()
        meta = IRConfigMeta(source_vendor="cisco", target_vendor="huawei",
            source_domain=DeviceDomain.SWITCH, target_domain=DeviceDomain.SWITCH,
            source_platform="ios-xe", target_platform="vrp")
        ir = IRConfig(meta=meta)
        span = SourceSpan(start_line=1, end_line=1)
        ir.unknown_blocks.append(IRUnknownBlock(type=IRType.UNKNOWN, source_span=span, raw_text="vlan 10"))
        result = r.render(ir)
        # Huawei uses # for comments
        assert "# Generated by" in result.config_text
        assert "# vlan 10" in result.config_text
        assert "! vlan 10" not in result.config_text

    def test_firewall_renderer_registered(self):
        init_renderers()
        for key in ["usg", "stoneos", "tos", "dp-firewall"]:
            cls = get_renderer(DeviceDomain.FIREWALL, key)
            assert cls is not None, f"FIREWALL renderer {key} not registered"

    def test_features_rendered_list(self):
        init_renderers()
        cls = get_renderer(DeviceDomain.SWITCH, "ios-xe")
        r = cls()
        meta = IRConfigMeta(source_vendor="h3c", target_vendor="cisco",
            source_domain=DeviceDomain.SWITCH, target_domain=DeviceDomain.SWITCH,
            source_platform="comware", target_platform="ios-xe")
        ir = IRConfig(meta=meta)
        result = r.render(ir)
        assert isinstance(result.features_rendered, list)
