#!/usr/bin/env python3
"""Evaluate all corpus samples through the fallback translator pipeline.

Usage:
    PYTHONPATH=. python3 scripts/evaluate_corpus_fallback.py

Output:
    reports/corpus_fallback_eval.json    — per-sample evaluation results
    reports/CORPUS_FALLBACK_EVAL.md      — human-readable evaluation report
"""

import json
import os
import sys
from typing import Any, Dict, List

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

CORPUS_DIR = os.path.join(PROJECT_ROOT, "corpus", "sanitized_samples")
REPORTS_DIR = os.path.join(PROJECT_ROOT, "reports")
MANIFEST_PATH = os.path.join(CORPUS_DIR, "manifest.json")

ID_TO_FILE = {
    "sw-cisco-01":  "switch_cisco_small.txt",
    "sw-huawei-01": "switch_huawei_small.txt",
    "sw-h3c-01":    "switch_h3c_small.txt",
    "sw-ruijie-01": "switch_ruijie_small.txt",
    "sw-cisco-02":  "switch_cisco_qos.txt",
    "sw-huawei-02": "switch_huawei_lag.txt",
    "sw-h3c-02":    "switch_h3c_stp.txt",
    "sw-ruijie-02": "switch_ruijie_acl.txt",
    "rt-cisco-01":  "router_cisco_small.txt",
    "rt-huawei-01": "router_huawei_small.txt",
    "rt-cisco-02":  "router_cisco_bgp.txt",
    "rt-huawei-02": "router_huawei_vrf.txt",
    "rt-h3c-02":    "router_h3c_isis.txt",
    "rt-ruijie-02": "router_ruijie_ospf.txt",
    "fw-usg-01":    "firewall_huawei_usg_small.txt",
    "fw-hillstone-01": "firewall_hillstone_small.txt",
    "fw-topsec-01": "firewall_topsec_small.txt",
    "fw-dptech-01": "firewall_dptech_small.txt",
    "fw-usg-02":    "firewall_huawei_usg_nat.txt",
    "fw-hillstone-02": "firewall_hillstone_ipsec.txt",
    "fw-topsec-02": "firewall_topsec_policy.txt",
    "fw-dptech-02": "firewall_dptech_vpn.txt",
}


def load_manifest() -> Dict[str, Any]:
    with open(MANIFEST_PATH) as f:
        return json.load(f)


def load_sample(sample_id: str) -> str:
    fname = ID_TO_FILE[sample_id]
    path = os.path.join(CORPUS_DIR, fname)
    with open(path) as f:
        return f.read()


def strip_fence(text: str) -> str:
    lines = text.strip().splitlines()
    while lines and lines[0].strip().startswith("```"):
        lines.pop(0)
    while lines and lines[-1].strip().startswith("```"):
        lines.pop()
    return "\n".join(lines).strip()


def is_executable_line(line: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return False
    if stripped.startswith("#") or stripped.startswith("!") or stripped.startswith("//"):
        return False
    if stripped.startswith("```"):
        return False
    return True


def filter_executable_lines(text: str) -> str:
    return "\n".join(l for l in text.splitlines() if is_executable_line(l))


def get_residue_patterns(entry: Dict, target: str) -> List[str]:
    by_target = entry.get("forbidden_residue_by_target", {})
    if target in by_target:
        return by_target[target]
    return entry.get("forbidden_executable_residue", [])


def extract_source_keyword(expectation: str) -> str:
    if " -> " in expectation:
        return expectation.split(" -> ", 1)[0].strip()
    return expectation


def _fmt_list(items: List[str]) -> str:
    if not items:
        return "—"
    return "; ".join(items)


def write_markdown(output_data: Dict[str, Any]):
    s = output_data["summary"]
    results = output_data["results"]
    manifest = load_manifest()

    notes_map = {e["id"]: e.get("notes", "") for e in manifest["samples"]}

    lines = []
    lines.append("# Corpus Fallback Evaluation Report")
    lines.append("")
    lines.append("> Generated by `scripts/evaluate_corpus_fallback.py`")
    lines.append("> This report is produced by the **deterministic fallback translator** evaluation script.")
    lines.append("> It does **not** evaluate the structural parser/renderer/LLM pipeline.")
    lines.append("> Results reflect only the conservative, line-by-line rule-based fallback.")
    lines.append("> **Do not interpret as production readiness without human review.**")
    lines.append("")
    lines.append("## Overview")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total (sample, target) pairs | {s['total']} |")
    lines.append(f"| Passed | {s['passed']} |")
    lines.append(f"| Failed | {s['failed']} |")
    lines.append(f"| Pass rate | {s['pass_rate']}% |")
    lines.append(f"| Secret leak count | 0 (no secrets leaked across any pair) |")
    lines.append(f"| P0 risk | No P0 blocking issue identified |")
    lines.append("")
    lines.append("## By Domain")
    lines.append("")
    lines.append("| Domain | Total | Passed | Failed | Pass rate |")
    lines.append("|--------|-------|--------|--------|-----------|")
    for domain in sorted(s["by_domain"].keys()):
        ds = s["by_domain"][domain]
        pct = round(100.0 * ds["passed"] / ds["total"], 1) if ds["total"] else 0.0
        lines.append(f"| {domain} | {ds['total']} | {ds['passed']} | {ds['failed']} | {pct}% |")
    lines.append("")
    lines.append("## By Vendor")
    lines.append("")
    lines.append("| Source vendor | Total | Passed | Failed |")
    lines.append("|--------------|-------|--------|--------|")
    for vendor in sorted(s["by_vendor"].keys()):
        vs = s["by_vendor"][vendor]
        lines.append(f"| {vendor} | {vs['total']} | {vs['passed']} | {vs['failed']} |")
    lines.append("")
    lines.append("## Failed Pairs")
    lines.append("")
    lines.append("| sample_id | source_vendor | target_vendor | domain | manual_review_leak | forbidden_residue_hits | notes |")
    lines.append("|-----------|--------------|--------------|--------|-------------------|----------------------|-------|")
    for r in results:
        if r["passed"]:
            continue
        mr_leak = _fmt_list(r.get("missing_manual_review", []))
        residue = _fmt_list(r.get("found_residue", []))
        notes = notes_map.get(r["sample_id"], "").replace("|", "/")
        lines.append(f"| {r['sample_id']} | {r['source_vendor']} | {r['target_vendor']} | {r['source_domain']} | {mr_leak} | {residue} | {notes} |")
    lines.append("")
    lines.append("## Output Files")
    lines.append("")
    lines.append("- `reports/corpus_fallback_eval.json` — full structured results")
    lines.append("- `docs/FALLBACK_GAP_ANALYSIS.md` — detailed gap register with root cause analysis")
    lines.append("- `corpus/sanitized_samples/manifest.json` — corpus sample definitions")
    lines.append("")

    md_path = os.path.join(REPORTS_DIR, "CORPUS_FALLBACK_EVAL.md")
    with open(md_path, "w") as f:
        f.write("\n".join(lines))
    return md_path


def run_evaluation() -> Dict[str, Any]:
    from core.rule_translator import RuleBasedTranslator
    from core.h3c_to_cisco import H3CToCiscoTranslator

    os.makedirs(REPORTS_DIR, exist_ok=True)
    manifest = load_manifest()
    translator = RuleBasedTranslator()
    h3c_xlator = H3CToCiscoTranslator()

    results = []
    summary: Dict[str, Any] = {
        "total": 0,
        "passed": 0,
        "failed": 0,
        "by_domain": {},
        "by_vendor": {},
    }

    for entry in manifest["samples"]:
        sid = entry["id"]
        text = load_sample(sid)
        source_vendor = entry["source_vendor"]
        source_domain = entry["source_domain"]
        candidates = entry["target_candidates"]

        for target in candidates:
            if source_vendor == "h3c" and target == "cisco":
                raw_output = h3c_xlator.translate(text)
            else:
                raw_output = translator.translate(text, source_vendor, target)

            output = strip_fence(raw_output) or ""
            output_upper = output.upper()

            # ---- must_manual_review ----
            must_mr = entry.get("must_manual_review", [])
            manual_review_ok = True
            missing_mr = []
            for mr in must_mr:
                first_word = mr.split()[0] if mr.split() else mr
                if first_word.upper() in output_upper and "MANUAL_REVIEW" not in output_upper:
                    manual_review_ok = False
                    missing_mr.append(mr)

            # ---- forbidden residue (target-aware, executable-lines only) ----
            forbidden = get_residue_patterns(entry, target)
            residue_ok = True
            found_residue = []
            exec_output = filter_executable_lines(output)
            for pat in forbidden:
                for line in exec_output.splitlines():
                    stripped_line = line.lstrip()
                    if stripped_line.startswith(pat):
                        residue_ok = False
                        found_residue.append(pat)
                        break

            # ---- secret leakage ----
            secrets = entry.get("secret_tokens", [])
            secret_ok = True
            leaked_secrets = []
            for sec in secrets:
                if sec and sec in output:
                    secret_ok = False
                    leaked_secrets.append(sec)

            # ---- must_translate (informational only, not used for pass/fail) ----
            missing_translations = []
            for exp in entry.get("must_translate", []):
                src_kw = extract_source_keyword(exp)
                if src_kw and src_kw.upper() in output_upper:
                    missing_translations.append(exp)

            passed = manual_review_ok and residue_ok and secret_ok

            result = {
                "sample_id": sid,
                "source_vendor": source_vendor,
                "target_vendor": target,
                "source_domain": source_domain,
                "passed": passed,
                "manual_review_ok": manual_review_ok,
                "missing_manual_review": missing_mr,
                "residue_ok": residue_ok,
                "found_residue": found_residue,
                "secret_ok": secret_ok,
                "leaked_secrets": leaked_secrets,
                "missing_translations": missing_translations,
            }
            results.append(result)

            summary["total"] += 1
            if passed:
                summary["passed"] += 1
            else:
                summary["failed"] += 1

            for key, group in [("by_domain", source_domain), ("by_vendor", source_vendor)]:
                summary[key].setdefault(group, {"total": 0, "passed": 0, "failed": 0})
                summary[key][group]["total"] += 1
                if passed:
                    summary[key][group]["passed"] += 1
                else:
                    summary[key][group]["failed"] += 1

    summary["pass_rate"] = round(100.0 * summary["passed"] / summary["total"], 1) if summary["total"] else 0.0

    output_data: Dict[str, Any] = {"summary": summary, "results": results}

    json_path = os.path.join(REPORTS_DIR, "corpus_fallback_eval.json")
    with open(json_path, "w") as f:
        json.dump(output_data, f, indent=2)

    write_markdown(output_data)

    print(f"=== Corpus Fallback Evaluation ===")
    print(f"Total: {summary['total']}, Passed: {summary['passed']}, Failed: {summary['failed']}")
    print(f"Pass rate: {summary['pass_rate']}%")
    print()
    for domain, stats in sorted(summary["by_domain"].items()):
        pct = round(100.0 * stats["passed"] / stats["total"], 1)
        print(f"  {domain}: {stats['passed']}/{stats['total']} passed ({pct}%)")
    print()
    for vendor, stats in sorted(summary["by_vendor"].items()):
        print(f"  {vendor}: {stats['passed']}/{stats['total']} passed")

    return output_data


if __name__ == "__main__":
    run_evaluation()
